openapi: 3.0.3
info:
  title: OpenAPI schema for template kubernetes-manifest-deployer
components:
  schemas:
    variables:
      type: object
      properties:
        manifest:
          title: Manifest
          type: string
          description: The manifest YAML to apply to kubernetes, only one K8s resource object is supported
          default: |
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              labels:
                app: nginx
              name: nginx
              namespace: default
            spec:
              replicas: 2
              selector:
                matchLabels:
                  app: nginx
              strategy: {}
              template:
                metadata:
                  labels:
                    app: nginx
                spec:
                  containers:
                  - image: nginx
                    name: nginx
                    resources: {}
          x-walrus-ui:
            group: Basic
            order: 1
            widget: YamlEditor
      x-walrus-ui:
        groupOrder:
        - Basic
